return {
  ensure_installed = {
    'bash',
    'c',
    'css',
    'diff',
    'html',
    'javascript',
    'json',
    'lua',
    'git_config',
    'gitcommit',
    'git_rebase',
    'gitignore',
    'gitattributes',
    'nix',
    'markdown',
    'markdown_inline',
    'php',
    'regex',
    'rust',
    'ssh_config',
    'sql',
    'toml',
    'typescript',
    'vim',
    'yaml',
    'vimdoc',
  },
  sync_install = true,
  highlight = { enable = true, additional_vim_regex_highlighting = false },
  indent = { enable = true },
  incremental_selection = {
    enable = true,
    keymaps = {
      init_selection = '<C-space>',
      node_incremental = '<C-space>',
      scope_incremental = false,
      node_decremental = '<bs>',
    },
  },
}
